package dfscript

import "github.com/df-mc/dragonfly/server/world/biome"

func (r *Runtime) setupBiome() error {
	return newObject().
		Const("badlands", biome.Badlands{}).
		Const("badlandsPlateau", biome.BadlandsPlateau{}).
		Const("bambooJungle", biome.BambooJungle{}).
		Const("bambooJungleHills", biome.BambooJungleHills{}).
		Const("basaltDeltas", biome.BasaltDeltas{}).
		Const("beach", biome.Beach{}).
		Const("birchForest", biome.BirchForest{}).
		Const("birchForestHills", biome.BirchForestHills{}).
		Const("cherryGrove", biome.CherryGrove{}).
		Const("coldOcean", biome.ColdOcean{}).
		Const("crimsonForest", biome.CrimsonForest{}).
		Const("darkForest", biome.DarkForest{}).
		Const("darkForestHills", biome.DarkForestHills{}).
		Const("deepColdOcean", biome.DeepColdOcean{}).
		Const("deepDark", biome.DeepDark{}).
		Const("deepFrozenOcean", biome.DeepFrozenOcean{}).
		Const("deepLukewarmOcean", biome.DeepLukewarmOcean{}).
		Const("deepOcean", biome.DeepOcean{}).
		Const("deepWarmOcean", biome.DeepWarmOcean{}).
		Const("desert", biome.Desert{}).
		Const("desertHills", biome.DesertHills{}).
		Const("desertLakes", biome.DesertLakes{}).
		Const("dripstoneCaves", biome.DripstoneCaves{}).
		Const("end", biome.End{}).
		Const("erodedBadlands", biome.ErodedBadlands{}).
		Const("flowerForest", biome.FlowerForest{}).
		Const("forest", biome.Forest{}).
		Const("frozenOcean", biome.FrozenOcean{}).
		Const("frozenPeaks", biome.FrozenPeaks{}).
		Const("frozenRiver", biome.FrozenRiver{}).
		Const("giantSpruceTaigaHills", biome.GiantSpruceTaigaHills{}).
		Const("giantTreeTaigaHills", biome.GiantTreeTaigaHills{}).
		Const("gravellyMountainsPlus", biome.GravellyMountainsPlus{}).
		Const("grove", biome.Grove{}).
		Const("iceSpikes", biome.IceSpikes{}).
		Const("jaggedPeaks", biome.JaggedPeaks{}).
		Const("jungle", biome.Jungle{}).
		Const("jungleEdge", biome.JungleEdge{}).
		Const("jungleHills", biome.JungleHills{}).
		Const("legacyFrozenOcean", biome.LegacyFrozenOcean{}).
		Const("lukewarmOcean", biome.LukewarmOcean{}).
		Const("lushCaves", biome.LushCaves{}).
		Const("mangroveSwamp", biome.MangroveSwamp{}).
		Const("meadow", biome.Meadow{}).
		Const("modifiedBadlandsPlateau", biome.ModifiedBadlandsPlateau{}).
		Const("modifiedJungle", biome.ModifiedJungle{}).
		Const("modifiedJungleEdge", biome.ModifiedJungleEdge{}).
		Const("modifiedWoodedBadlandsPlateau", biome.ModifiedWoodedBadlandsPlateau{}).
		Const("mountainEdge", biome.MountainEdge{}).
		Const("mushroomFieldShore", biome.MushroomFieldShore{}).
		Const("mushroomFields", biome.MushroomFields{}).
		Const("netherWastes", biome.NetherWastes{}).
		Const("ocean", biome.Ocean{}).
		Const("oldGrowthBirchForest", biome.OldGrowthBirchForest{}).
		Const("oldGrowthPineTaiga", biome.OldGrowthPineTaiga{}).
		Const("oldGrowthSpruceTaiga", biome.OldGrowthSpruceTaiga{}).
		Const("paleGarden", biome.PaleGarden{}).
		Const("plains", biome.Plains{}).
		Const("river", biome.River{}).
		Const("savanna", biome.Savanna{}).
		Const("savannaPlateau", biome.SavannaPlateau{}).
		Const("shatteredSavannaPlateau", biome.ShatteredSavannaPlateau{}).
		Const("snowyBeach", biome.SnowyBeach{}).
		Const("snowyMountains", biome.SnowyMountains{}).
		Const("snowyPlains", biome.SnowyPlains{}).
		Const("snowySlopes", biome.SnowySlopes{}).
		Const("snowyTaiga", biome.SnowyTaiga{}).
		Const("snowyTaigaHills", biome.SnowyTaigaHills{}).
		Const("snowyTaigaMountains", biome.SnowyTaigaMountains{}).
		Const("soulSandValley", biome.SoulSandValley{}).
		Const("stonyPeaks", biome.StonyPeaks{}).
		Const("stonyShore", biome.StonyShore{}).
		Const("sunflowerPlains", biome.SunflowerPlains{}).
		Const("swamp", biome.Swamp{}).
		Const("swampHills", biome.SwampHills{}).
		Const("taiga", biome.Taiga{}).
		Const("taigaHills", biome.TaigaHills{}).
		Const("taigaMountains", biome.TaigaMountains{}).
		Const("tallBirchHills", biome.TallBirchHills{}).
		Const("warmOcean", biome.WarmOcean{}).
		Const("warpedForest", biome.WarpedForest{}).
		Const("windsweptForest", biome.WindsweptForest{}).
		Const("windsweptGravellyHills", biome.WindsweptGravellyHills{}).
		Const("windsweptHills", biome.WindsweptHills{}).
		Const("windsweptSavanna", biome.WindsweptSavanna{}).
		Const("woodedBadlandsPlateau", biome.WoodedBadlandsPlateau{}).
		Const("woodedHills", biome.WoodedHills{}).
		Apply(r.vm, "biome")
}
